#:schema node_modules/wrangler/config-schema.json
name = "build-hang-repro"
main = "dist/index.js"
compatibility_date = "2024-04-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:worker"
